#!/usr/bin/env python
# -*- coding:utf-8 -*-
import tornado.ioloop
import tornado.web
import json
from db import mongoOps
import pdb
from  proj_log import log
class usersHandler(tornado.web.RequestHandler):

      # 检查账号是否存在
      def checkUser(self,userName):
          if userName == None:
             raise ValueError('参数不能为空') 
          result=mongoOps.db().login.find_one({'name':userName})
          if result:
             self.write({'status':1,'msg':1})
          else:
             self.write({'status':1,'msg':0})
          self.finish() 

      # 添加用户
      def addUser(self,name,password,role,email,product):
          user={'name':'default','password':'default','role':0,'email':'itoa@xxx.com','product':[]}
          user['name']=name
          user['password']=password
          user['role']=role
          user['email']=email
          user['product']=product
          mongoOps.db().login.insert(user)
          

      # 删除用户
      def delUser(self):
        pass
         
      def login(self,name,passwd,role):
	  try:
             log().debug('login::'+name+ ' '+passwd+ ' ' +str(role))
             result=mongoOps.db().login.find_one({'name':name,'role':role},{'_id':0})
             #pdb.set_trace()
             log().debug('login::query mongodb'+str(result))
             if result is None:
                self.write({'status':0,'message':'账号不存在,或账号权限非法！'})
                log().info('login::账号不存在,或账号权限非法！')
                self.finish()
             else:
                if passwd == result['password']:
                   self.write({'status':1,'message':'登录成功!'})
                   log().info('login::'+name+' login success')
                   self.finish()       
                else:
                   self.write({'status':0,'message':'密码错误!'})
                   log().info('login::密码错误！')
                   self.finish() 
          except Exception , err:
                self.write({'status':0,'message':'登录异常，异常为:'+str(err)})   
                log().error('login::登录异常，异常为'+str(err))
		self.finish()

      @tornado.web.asynchronous
      def post(self):
          try:
             pdb.set_trace()
             log().info('login::user start login')
             body = json.loads(self.request.body)
             operType=body['type']
             if operType == 'login':
                name=body['name']
	        password=body['password']
	        role=body['role']
                self.login(name,password,role)
             elif operType == 'checkUser':
                name=body['name']
                self.checkUser(name)
             elif operType == 'addUser':
                name=body['name']
	        password=body['password']
	        role=body['role']
                email=body['email'] 
                product1=body['product']
                product= json.loads(product1)
                self.addUser(name,password,role,email,product)
             elif operType == 'delUser':
                self.delUser()
             else:
                self.write({"status":0,"message":"调用/api/v1/users/接口异常,请检查参数类型!"})
                log().error('调用/api/v1/users接口异常，请检查参数')
                self.finish()
          except Exception ,e :
                self.write({"status":0,"message":"JSon解析数据异常,出错为"+str(e)})
                log().error({"status":0,"message":"JSon解析数据异常,出错为"+str(e)})
                self.finish()
                
